name: Unicorn Brain Automation Tests
on: [push]

jobs:
  unicorn-brain-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Node Installation
        uses: actions/setup-node@v1
        with:
          node-version: "18"

      - name: Global Newman
        run: |
          npm install -g newman
          npm install -g newman newman-reporter-htmlextra

      - name: Run Collection with OAuth2.0
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: |
          newman run dev-unicorn-ai.postman_collection.json \
            -e non-prod.postman_environment.json \
            --env-var "client_secret=$CLIENT_SECRET" \
            --reporters htmlextra

      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: newman-reports
          path: newman/

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Demo newman collection"
          push_options: "--force"
          env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          run: |
            echo "Starting Git Commit and Push"
            git status  # Add this line to see the repository status before the commit and push.
            git commit -am "Demo newman collection"
            git push --force
            echo "Git Commit and Push completed"
